version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "12"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run eslint
workflows:
  build-and-test:
    jobs:
      - build-and-test
